platform :ios, '9.0'
use_frameworks!

def corekit_pods
    pod 'CocoaLumberjack', '3.6.1'
    pod 'Alamofire', '4.9.1'
    pod 'Mantle', '2.0.2'
    pod 'MTLManagedObjectAdapter', '1.0.3'
end

    project 'IBMECMCoreSample/IBMECMCoreSample.xcodeproj'

target :'IBMECMCoreSampleApp' do
    project 'IBMECMCoreSample/IBMECMCoreSample.xcodeproj'

    corekit_pods
end

workspace 'navigatorMobileSDK'
