platform :ios, '9.0'
use_frameworks!

def corekit_pods
    pod 'CocoaLumberjack', '1.9.2'
    pod 'Alamofire', '4.0'
    pod 'Mantle', '2.0.2'
    pod 'MTLManagedObjectAdapter', '1.0.2'
end

    project 'IBMECMCoreSample/IBMECMCoreSample.xcodeproj'

target :'IBMECMCoreSampleApp' do
    project 'IBMECMCoreSample/IBMECMCoreSample.xcodeproj'

    corekit_pods
end

workspace 'navigatorMobileSDK'
